include(CheckCXXCompilerFlag)
include(CheckCCompilerFlag)
include(CheckAndAddWarnings)

function(CheckAndAddFlag flag)
	make_flag_for_check(${flag} checkedFlag)
    # Remove special chars
    string(MAKE_C_IDENTIFIER ${checkedFlag} VarName)
	check_cxx_compiler_flag(${checkedFlag} CXX_FLAG_${VarName}_SUPPORTED)
	check_c_compiler_flag(${checkedFlag} C_FLAG_${VarName}_SUPPORTED)
	if(CXX_FLAG_${VarName}_SUPPORTED)
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${flag}" PARENT_SCOPE)
	endif()
	if(C_FLAG_${VarName}_SUPPORTED)
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${flag}" PARENT_SCOPE)
	endif()
endfunction()

function(CheckAndAddFlags)
    foreach(flag ${ARGN})
        CheckAndAddFlag(${flag})
    endforeach()
endfunction()
